version: '3'
services:
  
    
  mysql:
    image: mysql:8
    container_name: meu-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: makequestions
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./dados-mysql:/var/lib/mysql

  app:
    build: .
    network_mode: "host"
    ports:
      - "5000:5000"
    volumes:
      - ./app.py:/app/app.py  # Mapeia o arquivo app.py externo
      - ./templates:/app/templates  # Mapeia o diretório de templates
      - ./static:/app/static  # Mapeia o diretório de arquivos estáticos
    stdin_open: true 
    tty: true

volumes:
    dados-mysql: